services:
  rafrsr_toggle_form_extension:
    class: Rafrsr\FormExtraBundle\Form\Extension\ToggleFormTypeExtension
    tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  rafrsr_embedded_template_form_type:
      class: Rafrsr\FormExtraBundle\Form\Type\EmbeddedTemplateType
      arguments: ['@templating']
      tags:
          - { name: form.type }

  rafrsr_datepicker_type_guesser:
        class: Rafrsr\FormExtraBundle\Form\Guesser\DatePickerTypeGuesser
        arguments: ['@doctrine']
        tags:
            - { name: form.type_guesser }

  rafrsr_switchery_type_guesser:
        class: Rafrsr\FormExtraBundle\Form\Guesser\SwitcheryTypeGuesser
        arguments: ['@doctrine']
        tags:
            - { name: form.type_guesser }